# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f690b8561b94e63fba2c3a02f6379ccd1a3d3c39dbad98b1ccc5045b1127c764e468a69fd761cab9269f024da11da368cf2843c3d449441d63267b09c1df6ce

test:
  secret_key_base: 1251ad5c4f2d9f4ab32e99fed9b0a8e53c91ba3e6c733c82629b93a41a59b09ec080b9f9b29ceb489bd321ca0b905f5802af4b305a840f008bca17a0e6991606

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
